let dayref = document.querySelector('.day_Week');
let month_year = document.querySelector('.month_year');
let dayOfWeek = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday",];
let monthOfYear =["January","February","March"," April","May","June","July"," August","September","October ","November ","December",];
let dateToday = new Date();
let dayToday = dateToday.getDay();
dayref.innerHTML = `${dayOfWeek[dayToday]}`;
let = monthDate = new Date();
let month = monthDate.getMonth();
let date = monthDate.getDate();
let year = monthDate.getFullYear();
month_year.innerHTML =`${monthOfYear[month]},    ${date}     ${year}` ;
